// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBoF6obkunWn8FqNA0aAsKYt6EwovStjY',
    appId: '1:648331041043:web:eb8dc370cf71f2f770e2e6',
    messagingSenderId: '648331041043',
    projectId: 'salon-booking-8bc5a',
    authDomain: 'salon-booking-8bc5a.firebaseapp.com',
    storageBucket: 'salon-booking-8bc5a.appspot.com',
    measurementId: 'G-C9FDR5DBSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_4xkYNzO13ju7nLTGtpsEdW1zovD78eQ',
    appId: '1:648331041043:android:17884d294b58fa9270e2e6',
    messagingSenderId: '648331041043',
    projectId: 'salon-booking-8bc5a',
    storageBucket: 'salon-booking-8bc5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhpbecacBGuHkcz2rfTUavsQQQe-bPOl8',
    appId: '1:648331041043:ios:028383a41de7b95570e2e6',
    messagingSenderId: '648331041043',
    projectId: 'salon-booking-8bc5a',
    storageBucket: 'salon-booking-8bc5a.appspot.com',
    iosClientId: '648331041043-5oq4nb46bfmh22vio9nsji2k8fq0uri8.apps.googleusercontent.com',
    iosBundleId: 'com.amon.salonBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhpbecacBGuHkcz2rfTUavsQQQe-bPOl8',
    appId: '1:648331041043:ios:028383a41de7b95570e2e6',
    messagingSenderId: '648331041043',
    projectId: 'salon-booking-8bc5a',
    storageBucket: 'salon-booking-8bc5a.appspot.com',
    iosClientId: '648331041043-5oq4nb46bfmh22vio9nsji2k8fq0uri8.apps.googleusercontent.com',
    iosBundleId: 'com.amon.salonBookingApp',
  );
}
